### ISSUE TITLE
可否说明一下测试的操作系统？

### ISSUE THREAD

**Issue by KFERMercer** [xulihang/Loongson-3A5000-Barcode-Reading-Test#1]
有劳。我使用 Kylin-Server-Loongarch64 测试发现并没有集成二进制翻译相关的组件，请问阁下使用的是哪家发行版？

**Comment by xulihang** [comment]
Loongnix. 贴吧吧主提供的ssh：http://tieba.baidu.com/p/7562976585?share=9105&fr=share&see_lz=0&sfc=copy&client_type=2&client_version=11.1.8.1&st=1644408836&unique=96D09380D753CFB321A4227AB19A9031

**Comment by KFERMercer** [comment]
好的, 了解了, 再次感谢
